version: "3.9"

services: 
  db:
    image: postgres
    container_name: review_it.db
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data: